### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by jcgrenier** [Teichlab/bracer#10]
Hello there,

I'm trying to install your program on one of our servers and I'm getting some sort of Python errors linked to the character encoding. Everything seems to work fine until the Kallisto step. Here's the error message I'm getting.

> ~/Programs/bracer/bracer test --ncores 12 --config_file ~/Programs/bracer/bracer.conf
====
##Making Kallisto indices##
Traceback (most recent call last):
  File "~/Programs/bracer/bracer", line 21, in <module>
    launch()
  File "~/Programs/bracer/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "~/Programs/bracer/bracerlib/tasks.py", line 1937, in run
    trimmed_fastq2=self.trimmed_fastq2).run()
  File "~/Programs/bracer/bracerlib/tasks.py", line 369, in run
    self.quantify(cell)
  File "~/Programs/bracer/bracerlib/tasks.py", line 605, in quantify
    self.trimmed_fastq2, self.keep_trimmed_reads)
  File "~/Programs/bracer/bracerlib/bracer_func.py", line 2103, in quantify_with_kallisto
    for line in infile:
  File "/home/apps/Logiciels/Python/python-3.5.1/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 32: ordinal not in range(128)

====

I tried different fixes in the bracer_func_py file at line 2104 like to change the 
line variable encoding using this:
                    line=line.decode('latin1').encode('ascii','replace')

It seems that it's bugging before this line anyway. Do you have any idea of what's going on?

Thanks a lot for your help!

Jean-Christophe

**Comment by idalind** [comment]
Hi Jean-Christophe,
Have you made sure to decompress the reference file containing your transcriptome sequences? This needs to be provided to Kallisto in plain-text fasta format.

Please let me know if this was not the issue.

Best,
Ida

**Comment by jcgrenier** [comment]
Hello Ida,

Thanks for your reply. I was in fact using directly the Kallisto index that I've prebuild. I'm using the fasta files directly now and it seems to work much better.

Thanks a lot!
