### ISSUE TITLE
Bracer test failing at Trinity step with empty read files

### ISSUE THREAD

**Issue by transcriptomics** [Teichlab/bracer#11]
$ bracer test -p 16 -c ./bracer.conf -o ./test
##Finding recombinant-derived reads##
Attempting new assembly for ['BCR_H', 'BCR_K', 'BCR_L']

Detected average R1 read length: 
50.0
Short read length detected. BraCeR will run two rounds of alignment for heavy chain

##BCR_H##
56438 reads; of these:
  56438 (100.00%) were paired; of these:
    35350 (62.64%) aligned concordantly 0 times
    21088 (37.36%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
    ----
    35350 pairs aligned concordantly 0 times; of these:
      73 (0.21%) aligned discordantly 1 time
    ----
    35277 pairs aligned 0 times concordantly or discordantly; of these:
      70554 mates make up the pairs; of these:
        69268 (98.18%) aligned 0 times
        232 (0.33%) aligned exactly 1 time
        1054 (1.49%) aligned >1 times
38.63% overall alignment rate
56438 reads; of these:
  56438 (100.00%) were paired; of these:
    56438 (100.00%) aligned concordantly 0 times
    0 (0.00%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
    ----
    56438 pairs aligned concordantly 0 times; of these:
      0 (0.00%) aligned discordantly 1 time
    ----
    56438 pairs aligned 0 times concordantly or discordantly; of these:
      112876 mates make up the pairs; of these:
        112876 (100.00%) aligned 0 times
        0 (0.00%) aligned exactly 1 time
        0 (0.00%) aligned >1 times
0.00% overall alignment rate
##BCR_K##
56438 reads; of these:
  56438 (100.00%) were paired; of these:
    48319 (85.61%) aligned concordantly 0 times
    8119 (14.39%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
    ----
    48319 pairs aligned concordantly 0 times; of these:
      114 (0.24%) aligned discordantly 1 time
    ----
    48205 pairs aligned 0 times concordantly or discordantly; of these:
      96410 mates make up the pairs; of these:
        95663 (99.23%) aligned 0 times
        195 (0.20%) aligned exactly 1 time
        552 (0.57%) aligned >1 times
15.25% overall alignment rate
##BCR_L##
56438 reads; of these:
  56438 (100.00%) were paired; of these:
    31766 (56.28%) aligned concordantly 0 times
    24672 (43.72%) aligned concordantly exactly 1 time
    0 (0.00%) aligned concordantly >1 times
    ----
    31766 pairs aligned concordantly 0 times; of these:
      270 (0.85%) aligned discordantly 1 time
    ----
    31496 pairs aligned 0 times concordantly or discordantly; of these:
      62992 mates make up the pairs; of these:
        61549 (97.71%) aligned 0 times
        144 (0.23%) aligned exactly 1 time
        1299 (2.06%) aligned >1 times
45.47% overall alignment rate

##Assembling Trinity Contigs##
##BCR_H##

     ______  ____   ____  ____   ____  ______  __ __
    |      ||    \ |    ||    \ |    ||      ||  |  |
    |      ||  D  ) |  | |  _  | |  | |      ||  |  |
    |_|  |_||    /  |  | |  |  | |  | |_|  |_||  ~  |
      |  |  |    \  |  | |  |  | |  |   |  |  |___, |
      |  |  |  .  \ |  | |  |  | |  |   |  |  |     |
      |__|  |__|\_||____||__|__||____|  |__|  |____/

Left read files: $VAR1 = [
          '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_H_1.fastq'
        ];
Right read files: $VAR1 = [
          '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_H_2.fastq'
        ];
Trinity version: __BLEEDING_EDGE__
\** NOTE: Latest version of Trinity is Trinity-v2.6.5, and can be obtained at:
        https://github.com/trinityrnaseq/trinityrnaseq/releases

Tuesday, February 13, 2018: 23:22:25    CMD: java -Xmx64m -XX:ParallelGCThreads=2  -jar /booleanfs/apps/trinityrnaseq-devel/util/support_scripts/ExitTester.jar 0
Tuesday, February 13, 2018: 23:22:25    CMD: java -Xmx64m -XX:ParallelGCThreads=2  -jar /booleanfs/apps/trinityrnaseq-devel/util/support_scripts/ExitTester.jar 1
Tuesday, February 13, 2018: 23:22:25    CMD: mkdir -p /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_H
Tuesday, February 13, 2018: 23:22:25    CMD: mkdir -p /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_H/chrysalis

\----------------------------------------------------------------------------------
\-------------- Trinity Phase 1: Clustering of RNA-Seq Reads  ---------------------
\----------------------------------------------------------------------------------

\---------------------------------------------------------------
\------------ In silico Read Normalization ---------------------
\-- (Removing Excess Reads Beyond 50 Coverage --
\---------------------------------------------------------------

\# running normalization on reads: $VAR1 = [
          [
            '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_H_1.fastq'
          ],
          [
            '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_H_2.fastq'
          ]
        ];

Tuesday, February 13, 2018: 23:22:25    CMD: /booleanfs/apps/trinityrnaseq-devel/util/insilico_read_normalization.pl --seqType fq --JM 12G  --max_cov 50 --min_cov 1 --CPU 16 --output /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_H/insilico_read_normalization   --max_pct_stdev 10000  --left /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_H_1.fastq --right /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_H_2.fastq --pairs_together --PARALLEL_STATS  
Converting input files. (both directions in parallel)CMD: seqtk-trinity seq -A /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_H_1.fastq >> left.fa
CMD: seqtk-trinity seq -A /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_H_2.fastq >> right.fa
CMD finished (0 seconds)
CMD finished (0 seconds)
Done converting input files.CMD: cat left.fa right.fa > both.fa
CMD finished (0 seconds)
\-------------------------------------------
\----------- Jellyfish  --------------------
\-- (building a k-mer catalog from reads) --
\-------------------------------------------

CMD: jellyfish count -t 16 -m 25 -s 100000000  --canonical  both.fa
CMD finished (2 seconds)
CMD: jellyfish histo -t 16 -o jellyfish.K25.min2.kmers.fa.histo mer_counts.jf
CMD finished (0 seconds)
CMD: jellyfish dump -L 2 mer_counts.jf > jellyfish.K25.min2.kmers.fa
CMD finished (0 seconds)
CMD: touch jellyfish.K25.min2.kmers.fa.success
CMD finished (0 seconds)
CMD: /booleanfs/apps/trinityrnaseq-devel/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads left.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 8  --DS  > left.fa.K25.stats
CMD: /booleanfs/apps/trinityrnaseq-devel/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads right.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 8  --DS  > right.fa.K25.stats
-reading Kmer occurrences...-reading Kmer occurrences...

 done parsing 0 Kmers, 0 added, taking 0 seconds.
STATS_GENERATION_TIME: 0 seconds.

 done parsing 0 Kmers, 0 added, taking 0 seconds.
STATS_GENERATION_TIME: 0 seconds.
CMD finished (0 seconds)
CMD finished (0 seconds)
-sorting each stats file by read name.
CMD: /booleanfs/sysapps/coreutilsv8.29/bin/sort --parallel=16 -k5,5 -T . -S 6G left.fa.K25.stats > left.fa.K25.stats.sort
CMD: /booleanfs/sysapps/coreutilsv8.29/bin/sort --parallel=16 -k5,5 -T . -S 6G right.fa.K25.stats > right.fa.K25.stats.sort
CMD finished (0 seconds)
CMD finished (0 seconds)
CMD: /booleanfs/apps/trinityrnaseq-devel/util/..//util/support_scripts//nbkc_merge_left_right_stats.pl --left left.fa.K25.stats.sort --right right.fa.K25.stats.sort --sorted > pairs.K25.stats
-opening left.fa.K25.stats.sort
-opening right.fa.K25.stats.sort
-done opening files.
CMD finished (0 seconds)
Error, pairs.K25.stats is empty.  Be sure to check your fastq reads and ensure that the read names are identical except for the /1 or /2 designation. at /booleanfs/apps/trinityrnaseq-devel/util/insilico_read_normalization.pl line 921.
Error, cmd: /booleanfs/apps/trinityrnaseq-devel/util/insilico_read_normalization.pl --seqType fq --JM 12G  --max_cov 50 --min_cov 1 --CPU 16 --output /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_H/insilico_read_normalization   --max_pct_stdev 10000  --left /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_H_1.fastq --right /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_H_2.fastq --pairs_together --PARALLEL_STATS   died with ret 512 at /booleanfs/apps/trinityrnaseq-devel/Trinity line 2578.
        main::process_cmd("/booleanfs/apps/trinityrnaseq-devel/util/insilico_read_normal"...) called at /booleanfs/apps/trinityrnaseq-devel/Trinity line 3124
        main::normalize("/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinit"..., 50, ARRAY(0xb41d60), ARRAY(0xb41d48)) called at /booleanfs/apps/trinityrnaseq-devel/Trinity line 3071
        main::run_normalization(50, ARRAY(0xb41d60), ARRAY(0xb41d48)) called at /booleanfs/apps/trinityrnaseq-devel/Trinity line 1291
Trinity failed for locus
##BCR_K##

     ______  ____   ____  ____   ____  ______  __ __
    |      ||    \ |    ||    \ |    ||      ||  |  |
    |      ||  D  ) |  | |  _  | |  | |      ||  |  |
    |_|  |_||    /  |  | |  |  | |  | |_|  |_||  ~  |
      |  |  |    \  |  | |  |  | |  |   |  |  |___, |
      |  |  |  .  \ |  | |  |  | |  |   |  |  |     |
      |__|  |__|\_||____||__|__||____|  |__|  |____/

Left read files: $VAR1 = [
          '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_K_1.fastq'
        ];
Right read files: $VAR1 = [
          '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_K_2.fastq'
        ];
Trinity version: __BLEEDING_EDGE__
\** NOTE: Latest version of Trinity is Trinity-v2.6.5, and can be obtained at:
        https://github.com/trinityrnaseq/trinityrnaseq/releases

Tuesday, February 13, 2018: 23:22:28    CMD: java -Xmx64m -XX:ParallelGCThreads=2  -jar /booleanfs/apps/trinityrnaseq-devel/util/support_scripts/ExitTester.jar 0
Tuesday, February 13, 2018: 23:22:28    CMD: java -Xmx64m -XX:ParallelGCThreads=2  -jar /booleanfs/apps/trinityrnaseq-devel/util/support_scripts/ExitTester.jar 1
Tuesday, February 13, 2018: 23:22:28    CMD: mkdir -p /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_K
Tuesday, February 13, 2018: 23:22:28    CMD: mkdir -p /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_K/chrysalis

\----------------------------------------------------------------------------------
\-------------- Trinity Phase 1: Clustering of RNA-Seq Reads  ---------------------
\----------------------------------------------------------------------------------

\---------------------------------------------------------------
\------------ In silico Read Normalization ---------------------
\-- (Removing Excess Reads Beyond 50 Coverage --
\---------------------------------------------------------------

\# running normalization on reads: $VAR1 = [
          [
            '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_K_1.fastq'
          ],
          [
            '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_K_2.fastq'
          ]
        ];

Tuesday, February 13, 2018: 23:22:28    CMD: /booleanfs/apps/trinityrnaseq-devel/util/insilico_read_normalization.pl --seqType fq --JM 12G  --max_cov 50 --min_cov 1 --CPU 16 --output /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_K/insilico_read_normalization   --max_pct_stdev 10000  --left /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_K_1.fastq --right /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_K_2.fastq --pairs_together --PARALLEL_STATS  
Converting input files. (both directions in parallel)CMD: seqtk-trinity seq -A /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_K_1.fastq >> left.fa
CMD: seqtk-trinity seq -A /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_K_2.fastq >> right.fa
CMD finished (0 seconds)
CMD finished (0 seconds)
CMD: touch left.fa.ok
CMD finished (0 seconds)
Done converting input files.CMD: cat left.fa right.fa > both.fa
CMD finished (0 seconds)
CMD: touch both.fa.ok
CMD finished (0 seconds)
\-------------------------------------------
\----------- Jellyfish  --------------------
\-- (building a k-mer catalog from reads) --
\-------------------------------------------

CMD: jellyfish count -t 16 -m 25 -s 100000000  --canonical  both.fa
CMD finished (2 seconds)
CMD: jellyfish histo -t 16 -o jellyfish.K25.min2.kmers.fa.histo mer_counts.jf
CMD finished (0 seconds)
CMD: jellyfish dump -L 2 mer_counts.jf > jellyfish.K25.min2.kmers.fa
CMD finished (0 seconds)
CMD: touch jellyfish.K25.min2.kmers.fa.success
CMD finished (0 seconds)
CMD: /booleanfs/apps/trinityrnaseq-devel/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads left.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 8  --DS  > left.fa.K25.stats
CMD: /booleanfs/apps/trinityrnaseq-devel/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads right.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 8  --DS  > right.fa.K25.stats
-reading Kmer occurrences...
-reading Kmer occurrences...

 done parsing 4712 Kmers, 4712 added, taking 0 seconds.

 done parsing 4712 Kmers, 4712 added, taking 0 seconds.
STATS_GENERATION_TIME: 0 seconds.
CMD finished (0 seconds)
STATS_GENERATION_TIME: 0 seconds.
CMD finished (0 seconds)
CMD: touch left.fa.K25.stats.ok
CMD finished (0 seconds)
-sorting each stats file by read name.
CMD: /booleanfs/sysapps/coreutilsv8.29/bin/sort --parallel=16 -k5,5 -T . -S 6G left.fa.K25.stats > left.fa.K25.stats.sort
CMD: /booleanfs/sysapps/coreutilsv8.29/bin/sort --parallel=16 -k5,5 -T . -S 6G right.fa.K25.stats > right.fa.K25.stats.sort
CMD finished (0 seconds)
CMD finished (0 seconds)
CMD: touch left.fa.K25.stats.sort.ok
CMD finished (0 seconds)
CMD: /booleanfs/apps/trinityrnaseq-devel/util/..//util/support_scripts//nbkc_merge_left_right_stats.pl --left left.fa.K25.stats.sort --right right.fa.K25.stats.sort --sorted > pairs.K25.stats
-opening left.fa.K25.stats.sort
-opening right.fa.K25.stats.sort
-done opening files.
CMD finished (0 seconds)
Error, pairs.K25.stats is empty.  Be sure to check your fastq reads and ensure that the read names are identical except for the /1 or /2 designation. at /booleanfs/apps/trinityrnaseq-devel/util/insilico_read_normalization.pl line 921.
Error, cmd: /booleanfs/apps/trinityrnaseq-devel/util/insilico_read_normalization.pl --seqType fq --JM 12G  --max_cov 50 --min_cov 1 --CPU 16 --output /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_K/insilico_read_normalization   --max_pct_stdev 10000  --left /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_K_1.fastq --right /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_K_2.fastq --pairs_together --PARALLEL_STATS   died with ret 512 at /booleanfs/apps/trinityrnaseq-devel/Trinity line 2578.
        main::process_cmd("/booleanfs/apps/trinityrnaseq-devel/util/insilico_read_normal"...) called at /booleanfs/apps/trinityrnaseq-devel/Trinity line 3124
        main::normalize("/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinit"..., 50, ARRAY(0x1555d30), ARRAY(0x1555d60)) called at /booleanfs/apps/trinityrnaseq-devel/Trinity line 3071
        main::run_normalization(50, ARRAY(0x1555d30), ARRAY(0x1555d60)) called at /booleanfs/apps/trinityrnaseq-devel/Trinity line 1291
Trinity failed for locus
##BCR_L##

     ______  ____   ____  ____   ____  ______  __ __
    |      ||    \ |    ||    \ |    ||      ||  |  |
    |      ||  D  ) |  | |  _  | |  | |      ||  |  |
    |_|  |_||    /  |  | |  |  | |  | |_|  |_||  ~  |
      |  |  |    \  |  | |  |  | |  |   |  |  |___, |
      |  |  |  .  \ |  | |  |  | |  |   |  |  |     |
      |__|  |__|\_||____||__|__||____|  |__|  |____/

Left read files: $VAR1 = [
          '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_L_1.fastq'
        ];
Right read files: $VAR1 = [
          '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_L_2.fastq'
        ];
Trinity version: __BLEEDING_EDGE__
** NOTE: Latest version of Trinity is Trinity-v2.6.5, and can be obtained at:
        https://github.com/trinityrnaseq/trinityrnaseq/releases

Tuesday, February 13, 2018: 23:22:31    CMD: java -Xmx64m -XX:ParallelGCThreads=2  -jar /booleanfs/apps/trinityrnaseq-devel/util/support_scripts/ExitTester.jar 0
Tuesday, February 13, 2018: 23:22:31    CMD: java -Xmx64m -XX:ParallelGCThreads=2  -jar /booleanfs/apps/trinityrnaseq-devel/util/support_scripts/ExitTester.jar 1
Tuesday, February 13, 2018: 23:22:31    CMD: mkdir -p /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_L
Tuesday, February 13, 2018: 23:22:31    CMD: mkdir -p /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_L/chrysalis

\----------------------------------------------------------------------------------
\-------------- Trinity Phase 1: Clustering of RNA-Seq Reads  ---------------------
\----------------------------------------------------------------------------------

\---------------------------------------------------------------
\------------ In silico Read Normalization ---------------------
\-- (Removing Excess Reads Beyond 50 Coverage --
\---------------------------------------------------------------

\# running normalization on reads: $VAR1 = [
          [
            '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_L_1.fastq'
          ],
          [
            '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_L_2.fastq'
          ]
        ];

Tuesday, February 13, 2018: 23:22:31    CMD: /booleanfs/apps/trinityrnaseq-devel/util/insilico_read_normalization.pl --seqType fq --JM 12G  --max_cov 50 --min_cov 1 --CPU 16 --output /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_L/insilico_read_normalization   --max_pct_stdev 10000  --left /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_L_1.fastq --right /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_L_2.fastq --pairs_together --PARALLEL_STATS  
Converting input files. (both directions in parallel)CMD: seqtk-trinity seq -A /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_L_1.fastq >> left.fa
CMD: seqtk-trinity seq -A /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_L_2.fastq >> right.fa
CMD finished (0 seconds)
CMD finished (0 seconds)
CMD: touch left.fa.ok
CMD finished (0 seconds)
Done converting input files.CMD: cat left.fa right.fa > both.fa
CMD finished (0 seconds)
CMD: touch both.fa.ok
CMD finished (0 seconds)
\-------------------------------------------
\----------- Jellyfish  --------------------
\-- (building a k-mer catalog from reads) --
\-------------------------------------------

CMD: jellyfish count -t 16 -m 25 -s 100000000  --canonical  both.fa
CMD finished (2 seconds)
CMD: jellyfish histo -t 16 -o jellyfish.K25.min2.kmers.fa.histo mer_counts.jf
CMD finished (0 seconds)
CMD: jellyfish dump -L 2 mer_counts.jf > jellyfish.K25.min2.kmers.fa
CMD finished (0 seconds)
CMD: touch jellyfish.K25.min2.kmers.fa.success
CMD finished (0 seconds)
CMD: /booleanfs/apps/trinityrnaseq-devel/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads left.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 8  --DS  > left.fa.K25.stats
CMD: /booleanfs/apps/trinityrnaseq-devel/util/..//Inchworm/bin/fastaToKmerCoverageStats --reads right.fa --kmers jellyfish.K25.min2.kmers.fa --kmer_size 25  --num_threads 8  --DS  > right.fa.K25.stats
-reading Kmer occurrences...
-reading Kmer occurrences...

 done parsing 13066 Kmers, 13066 added, taking 0 seconds.

 done parsing 13066 Kmers, 13066 added, taking 0 seconds.
STATS_GENERATION_TIME: 0 seconds.
CMD finished (0 seconds)
STATS_GENERATION_TIME: 0 seconds.
CMD finished (0 seconds)
CMD: touch left.fa.K25.stats.ok
CMD finished (0 seconds)
-sorting each stats file by read name.
CMD: /booleanfs/sysapps/coreutilsv8.29/bin/sort --parallel=16 -k5,5 -T . -S 6G left.fa.K25.stats > left.fa.K25.stats.sort
CMD: /booleanfs/sysapps/coreutilsv8.29/bin/sort --parallel=16 -k5,5 -T . -S 6G right.fa.K25.stats > right.fa.K25.stats.sort
CMD finished (0 seconds)
CMD finished (0 seconds)
CMD: touch left.fa.K25.stats.sort.ok
CMD finished (0 seconds)
CMD: /booleanfs/apps/trinityrnaseq-devel/util/..//util/support_scripts//nbkc_merge_left_right_stats.pl --left left.fa.K25.stats.sort --right right.fa.K25.stats.sort --sorted > pairs.K25.stats
-opening left.fa.K25.stats.sort
-opening right.fa.K25.stats.sort
-done opening files.
CMD finished (0 seconds)
Error, pairs.K25.stats is empty.  Be sure to check your fastq reads and ensure that the read names are identical except for the /1 or /2 designation. at /booleanfs/apps/trinityrnaseq-devel/util/insilico_read_normalization.pl line 921.
Error, cmd: /booleanfs/apps/trinityrnaseq-devel/util/insilico_read_normalization.pl --seqType fq --JM 12G  --max_cov 50 --min_cov 1 --CPU 16 --output /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_L/insilico_read_normalization   --max_pct_stdev 10000  --left /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_L_1.fastq --right /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/aligned_reads/cell1_BCR_L_2.fastq --pairs_together --PARALLEL_STATS   died with ret 512 at /booleanfs/apps/trinityrnaseq-devel/Trinity line 2578.
        main::process_cmd("/booleanfs/apps/trinityrnaseq-devel/util/insilico_read_normal"...) called at /booleanfs/apps/trinityrnaseq-devel/Trinity line 3124
        main::normalize("/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinit"..., 50, ARRAY(0xf14df0), ARRAY(0xf14dd8)) called at /booleanfs/apps/trinityrnaseq-devel/Trinity line 3071
        main::run_normalization(50, ARRAY(0xf14df0), ARRAY(0xf14dd8)) called at /booleanfs/apps/trinityrnaseq-devel/Trinity line 1291
Trinity failed for locus
No successful Trinity assemblies
##No recombinants found##

**Comment by idalind** [comment]
Hi,
I see that you are using the BLEEDING_EDGE version of Trinity. I'm not sure exactly which version this is and how old it is compared to Trinity-v2.4.0. BraCeR expects a Trinity version in the format of Trinity-v2.x.x in order to detect correct version. Could you please try to re-run the test using Trinity-v2.4.0? I will test BraCeR with later versions of Trinity and try to make it compatible with these versions as well.

**Comment by transcriptomics** [comment]
Thank you so much for your prompt reply. I am using the latest build of Trinity (2.6.5), which runs fine on other datasets. Older Trinity fails on my run environment.

The reason it says bleeding edge is because I had pulled and built Trinity from the devel branch at GitHub hours before the latest production release.

Btw Tracer runs fine when I issue “tracer test”.

**Comment by idalind** [comment]
Hi, I suspect this is an issue due to the in silico normalization not being turned off since BraCeR couldn't detect the Trinity version due to it's unexpected name. Could you please pull the newest commit for BraCeR (just updated) and add `trinity_version = BLEEDING_EDGE` under `[trinity_options]` in your config file? This should now be detected by BraCeR and in silico normalization will be turned off. Hopefully this will solve the issue with Trinity (although I cannot guarantee it since I haven't tested BraCeR for the newest versions). Please do let me know if it still doesn't work.

Best,
Ida

**Comment by transcriptomics** [comment]
I simply pulled the official release of Trinity 2.6.5 and after that no error while running Trinity-- bracer detected the 2.x.x format of Trinity version.  

However, the latest version of kallisto no longer has "--make-unique" option by default while making kallisto index. So I got a new error now while kallisto index was being made.


$ bracer test -p 12 -c ./bracer.conf -o ./test
##Finding recombinant-derived reads##
.
.
.
.
.
.
Thursday, February 15, 2018: 23:18:21   CMD: touch recursive_trinity.cmds.ok
Thursday, February 15, 2018: 23:18:21   CMD: touch recursive_trinity.cmds.ok


\--------------------------------------------------------------------------------
\------------ Trinity Phase 2: Assembling Clusters of Reads ---------------------
\--------------------------------------------------------------------------------

Thursday, February 15, 2018: 23:18:21   CMD: /booleanfs/apps/trinityrnaseqv2.6.5/trinity-plugins/BIN/ParaFly -c recursive_trinity.cmds -CPU 12 -v -shuffle 
Number of Commands: 1
succeeded(1)   100% completed.    

All commands completed successfully. :-)



\** Harvesting all assembled transcripts into a single multi-fasta file...

Thursday, February 15, 2018: 23:18:33   CMD: find /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_L/read_partitions/ -name '*inity.fasta'  | /booleanfs/apps/trinityrnaseqv2.6.5/util/support_scripts/partitioned_trinity_aggregator.pl TRINITY_DN > /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_L/Trinity.fasta.tmp
Thursday, February 15, 2018: 23:18:33   CMD: mv /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_L/Trinity.fasta.tmp /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_L.Trinity.fasta


\###################################################################
Butterfly assemblies are written to /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_L.Trinity.fasta
\###################################################################


Thursday, February 15, 2018: 23:18:33   CMD: /booleanfs/apps/trinityrnaseqv2.6.5/util/support_scripts/get_Trinity_gene_to_trans_map.pl /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_L.Trinity.fasta > /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/Trinity_output/Trinity_cell1_BCR_L.Trinity.fasta.gene_trans_map

##Running BLAST##
Performing Blast on ['BCR_H', 'BCR_K', 'BCR_L']
##BCR_H##
##BCR_K##
##BCR_L##

##Running IgBLAST##
Ig_seqtype: Ig
Performing IgBlast on ['BCR_H', 'BCR_K', 'BCR_L']
##BCR_H##
##BCR_K##
##BCR_L##

         START> MakeDB
       ALIGNER> IgBlast
ALIGNER_OUTPUT> cell1_BCR_K.fmt7
      SEQ_FILE> cell1_BCR_K.Trinity.fasta
      NO_PARSE> False
       PARTIAL> False
        SCORES> True
       REGIONS> True

PROGRESS> [23:18:46] Done                      0.0 min

PROGRESS> 23:18:46 |####################| 100% (1) 0.0 min

OUTPUT> /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/IgBLAST_output/cell1_BCR_K_db-pass.tab
  PASS> 1
  FAIL> 0
   END> MakeDb

         START> MakeDB
       ALIGNER> IgBlast
ALIGNER_OUTPUT> cell1_BCR_L.fmt7
      SEQ_FILE> cell1_BCR_L.Trinity.fasta
      NO_PARSE> False
       PARTIAL> False
        SCORES> True
       REGIONS> True

PROGRESS> [23:18:47] Done                      0.0 min

PROGRESS> 23:18:47 |####################| 100% (1) 0.0 min

OUTPUT> /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/IgBLAST_output/cell1_BCR_L_db-pass.tab
  PASS> 1
  FAIL> 0
   END> MakeDb



##Running Kallisto##
##Making Kallisto indices##

[build] loading fasta file /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/expression_quantification/kallisto_index/cell1_transcriptome.fa
[build] k-mer length: 31
Error: repeated name in FASTA file /booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/expression_quantification/kallisto_index/cell1_transcriptome.fa
ENST00000399012

Run with --make-unique to replace repeated names with unique names
Traceback (most recent call last):
  File "/booleanfs/sysapps/Pythonv3.6.4/bin/bracer", line 11, in <module>
    load_entry_point('bracer==0.1', 'console_scripts', 'bracer')()
  File "/booleanfs/sysapps/Pythonv3.6.4/lib/python3.6/site-packages/bracer-0.1-py3.6.egg/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/booleanfs/sysapps/Pythonv3.6.4/lib/python3.6/site-packages/bracer-0.1-py3.6.egg/bracerlib/tasks.py", line 1941, in run
    trimmed_fastq2=self.trimmed_fastq2).run()
  File "/booleanfs/sysapps/Pythonv3.6.4/lib/python3.6/site-packages/bracer-0.1-py3.6.egg/bracerlib/tasks.py", line 369, in run
    self.quantify(cell)
  File "/booleanfs/sysapps/Pythonv3.6.4/lib/python3.6/site-packages/bracer-0.1-py3.6.egg/bracerlib/tasks.py", line 605, in quantify
    self.trimmed_fastq2, self.keep_trimmed_reads)
  File "/booleanfs/sysapps/Pythonv3.6.4/lib/python3.6/site-packages/bracer-0.1-py3.6.egg/bracerlib/bracer_func.py", line 2110, in quantify_with_kallisto
    subprocess.check_call(index_command)
  File "/booleanfs/sysapps/Pythonv3.6.4/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/booleanfs/apps/kallisto_v0.44.0/kallisto', 'index', '-i', '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/expression_quantification/kallisto_index/cell1_transcriptome.idx', '/booleanfs/apps/Python3_pkgs/bracer/test/results/cell1/expression_quantification/kallisto_index/cell1_transcriptome.fa']' returned non-zero exit status 1.

**Comment by idalind** [comment]
@transcriptomics could you please try to use an earlier version of Kallisto until I have fixed compatibility with the newest version? I am currently using Kallisto v.0.43.0, so this should work.

Best,
Ida
