### ISSUE TITLE
Kallisto Transcriptomes

### ISSUE THREAD

**Issue by JohnMCMa** [Teichlab/bracer#20]
The [Kallisto transcriptome link](http://bio.math.berkeley.edu/kallisto/transcriptomes/) provided in readme.md no longer works; http://bio.math.berkeley.edu/kallisto/ redirects to [the software's Github page](http://pachterlab.github.io/kallisto/), and that page says that they no longer provide indexes for download, because indexing it locally is faster than downloading it.

In this case, it'd be helpful to provide the cDNA libraries you have tested for BraCeR, if it's not feasible to put them on this repo for download.

**Comment by dcroote** [comment]
These [couple lines of the Dockerfile](https://github.com/Teichlab/bracer/blob/726d773acd268850fac4753bd792887857cc89d2/Dockerfile#L63-L66) could help

**Comment by JohnMCMa** [comment]
That should be on the documentation as well. Not everyone use Docker; the vluster I'm using will *not* allow Docker, for example.

**Comment by idalind** [comment]
Thank you for the tip @dcroote . I have now updated the documentation with the relevant code taken from the Docker documentation, which enables users not using Docker to download and parse the transcriptome reference sequences.
