### ISSUE TITLE
Change-o/DefineClones.py ceases to have subcommands after 2018-01-10

### ISSUE THREAD

**Issue by JohnMCMa** [Teichlab/bracer#23]
Currently line 2163-2166 of bracer_func.py reads:
````
command = [DefineClones, "bygroup", '-d', changeo_input, '--mode', 'gene', '--act', 'set',  
                        '--model', model, '--dist', dist, '--sf', "JUNCTION", '--norm', 'len'] 
 
subprocess.check_call(command)
````
which calls `DefineClones.py bygroup [...]`. However, [after 2018-01-10](https://bitbucket.org/kleinstein/changeo/history-node/17488441e016/bin/DefineClones.py?at=default), DefineClones.py will no longer have subcommands since "bygroup" will be the only method used. Thus, `subprocess.check_call` will throw an error if the user's changeo is cloned after this date.

There should be version check on DefineClones.py, and change to command list accordingly if the version is larger or equal to 0.3.9.9999.

**Comment by idalind** [comment]
Thanks for the info! I have now added a version check and changed the command accordingly.
