### ISSUE TITLE
getting transcriptome files from gencode code broken link

### ISSUE THREAD

**Issue by michael-swift** [Teichlab/bracer#27]
From the installation instructions: 
`mkdir GRCh38 && cd GRCh38 && wget ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_27/gencode.v27.transcripts.fa.gz && \
gunzip gencode.v27.transcripts.fa.gz && python3 /path/to/bracer/docker_helper_files/gencode_parse.py gencode.v27.trans`

Yields 
--2018-12-17 14:30:40--  ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_27/gencode.v27.transcripts.fa.gz
           => ‘gencode.v27.transcripts.fa.gz’
Resolving ftp.sanger.ac.uk (ftp.sanger.ac.uk)... 193.62.203.115
Connecting to ftp.sanger.ac.uk (ftp.sanger.ac.uk)|193.62.203.115|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/gencode/Gencode_human/release_27 ... 
No such directory ‘pub/gencode/Gencode_human/release_27’

**Comment by michael-swift** [comment]
`mkdir GRCh38 && cd GRCh38 && wget ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.transcripts.fa.gz  && gunzip gencode.v29.transcripts.fa.gz && python3 /path/to/bracer/docker_helper_files/gencode_parse.py gencode.v29.trans` 

This seems to work

**Comment by yiskaN** [comment]
can you fix the link in the README so it will not make problems?
