### ISSUE TITLE
BLAST step gives error and stops

### ISSUE THREAD

**Issue by SabrinaITNL** [Teichlab/bracer#43]
Hi, 
I managed to install all the dependence and run few test with Bracer.
I always mange to obtained the assembled BCR sequences with Trinity.
Then when the BLAST step starts, it always stops giving this error: 
Command line argument error: Argument "query". File is not accessible:  `[...]/Trinity_output/A1_TEST_BCR_H.Trinity.fasta'

So somehow is not able to open the assembled fasta file?
Any suggestion on how I might resolve this?

Thank you very much for the attention
BW
Sabrina

**Comment by mstubb** [comment]
Hi Sabrina, 

A couple of questions:

1. Does `bracer test` work for you?

2. What command are you running that gives you this error?

3. What does BraCeR write to the output directory before dying with this error?

Thanks and best wishes,

Mike

**Comment by SabrinaITNL** [comment]
Hi Mike, 

1. even when running bracer test everything stop at the BLAST step and gives me the same error (--> error.txt)
2. I just run "bracer test" (configuration file --> bracerCONF.txt)
3. I have data in the cell1/aligned_reads (17 items), in the cell1/Trinity_Output (6 items) and I have 1 file in the cell1/BLAST_ouput folder (cell1_BCR_K.xml). 
Now that I notice, the cell1_BCR_H_1.fastq and cell1_BCR_H_2.fastq files in the aligned_reads folder are empty (0Kb) and I miss a Trinity_cell1_BCR_H.Trinity.fasta file in the Trinity/Ouput. Is that normal?

Cheers
Sabrina
[error.txt](https://github.com/Teichlab/bracer/files/4040572/error.txt)
[bracerCONF.txt](https://github.com/Teichlab/bracer/files/4040578/bracerCONF.txt)

**Comment by mstubb** [comment]
Hmm. I think I'll leave this to @idalind to chime in on what might be happening here. 

Best,

Mike

**Comment by SabrinaITNL** [comment]
Any chance @idalind will comment soon? :)

**Comment by idalind** [comment]
Hi @SabrinaITNL , sorry about the late reply! I've been busy the last few months submitting my PhD thesis, and didn't realise that I no longer receive email notifications from github. I will look into this issue in the next few days and get back to you.

**Comment by idalind** [comment]
@SabrinaITNL Did you try running bracer test with -c bracerCONF.txt ?
Also, could you please send me the log/errors you get from the entire run until it crashes?

**Comment by idalind** [comment]
Also, this may be an issue with bowtie and/or Trinity versions, since you do not get the expected outcome of cell1 after the alignment step with bowtie. BraCeR was developed with  bowtie2 v2.2.8 and Trinity v.2.4.0. Is it possible to try to run bracer again using these versions?
