### ISSUE TITLE
Docker image: FASTQ not found

### ISSUE THREAD

**Issue by SabrinaITNL** [Teichlab/bracer#44]
Hi, 
I tried to install and run Bracer but got stuck with an issue that is still unanswered (Issue#43, https://github.com/Teichlab/bracer/issues/43).

Therefore I tried to run the DOCKER image but got this error: OSError: [Errno 2] FASTQ file not found.

The command I used is: 
docker run -it --rm -v $PWD:/scratch -w /scratch teichlab/bracer assemble --single_end --fragment_length 75 --fragment_sd 1 A1 output SS2-18-006-A1_S1_merged_R1_001.fastq

Any idea why the FASTQ file can't be found?

Thank you for the help!

Best regards,
Sabrina

**Comment by mstubb** [comment]
Are you running that command from within the directory that contains the file `A1 output SS2-18-006-A1_S1_merged_R1_001.fastq`?

If so I think the spaces in the file name are probably breaking it, try putting quotes around the file name or renaming to remove spaces. 

Mike

**Comment by SabrinaITNL** [comment]
Hi Mike, 
the file name is SS2-18-006-A1_S1_merged_R1_001.fastq.
A1 and output ate the <cell_name> <output_directory> of the assemble command.

And yes I am running the command from the directory that contains the fastq file. 
I am using the Docker toolbox on windows. The directory is a mounted directory (so added as shared folder). 

I hope this is enough informatio.
BW
Sabrina

**Comment by mstubb** [comment]
Does `docker run -it --rm -v $PWD:/scratch -w /scratch teichlab/bracer test -o test_data` work if you run it from the directory into which you cloned BraCeR? 

M

**Comment by SabrinaITNL** [comment]
I get this error: 
cd teFileNotFoundError: [Errno 2] No such file or directory: '/scratch/test_data/results

**Comment by mstubb** [comment]
This is going to be very hard to debug remotely (I think it's possibly some combination of factors to do with where things are installed and how Docker is set up). Is there someone at your institute who can assist in person?

**Comment by SabrinaITNL** [comment]
Nope :(
To me it looks like I can't link my working directory to the /scratch folder in the docker image.
But I guess that's indeed more a "docker" problem rather then a"BraCer" problem.

Thank you anyway for your quick reply!
I'll look further on how to make BraCer work on my data...

BW
Sabrina

**Comment by dcroote** [comment]
@SabrinaITNL - I just tested the docker command:

`docker run -it --rm -v $PWD:/scratch -w /scratch teichlab/bracer test -o test_data`

and I believe the error you are seeing is because the `test_data/results` directory structure has to already exist on your *local* machine relative to where you are running the docker command. Try running `mkdir -p test_data/results` before running the above.
