### ISSUE TITLE
Docker image Trinity "No recombinats found"

### ISSUE THREAD

**Issue by SabrinaITNL** [Teichlab/bracer#45]
Hi, 
I am running Bracer on the docker image.
I already tried two files and they both stop at the Trinity step with the following comment:
Trinity run failed. Must investigate error above.
Trinity failed for locus
No successful Trinity assemblies
##No recombinants found##

Any idea on how can I solve this?
Thanks! :)
Sabrina

**Comment by mstubb** [comment]
Does `bracer test` work on your docker image now? 

If so, can you run on all your cells? It may be that the two you've tried just don't contain sequences that can be assembled.

M

**Comment by SabrinaITNL** [comment]
Hi Mike, 
nope, also the test fails. Might it be because the memory allocated to the VM is too little?
Which is the minimum amount required?
Cheers
Sabrina

**Comment by mstubb** [comment]
Ah, yes. That could well be why. Can you try 6 or 8GB? 

Mike
