### ISSUE TITLE
How to get the nice clonal network graph as in Nat.Methods publication?

### ISSUE THREAD

**Issue by SabrinaITNL** [Teichlab/bracer#49]
Hi, 
I run bracer summarise with default settings (summarise --graph_format pdf), but it seems I can't get the same graph layout for the clonal network as the one you show in Fig1A of the Nat.Methods publication (and in Supp.Figure SN7.1/2). 
The problem with my graph is that all the circles (== clonotypes) are allineated and not scattered around as in Fig1. Also, I don't get any legend for Ig subtypes and productive/unproductive chains.

Is there a special option I need to set to get the same output? Or did you actually modified the output with another program (like Illustrator) to get it in the nice layout of the publication?

Thank youfor the attention!
BW
Sabrina

**Comment by idalind** [comment]
Hi Sabrina,

Unfortunately the network output has to be edited in Illustrator or some other program to make it more suitable for publication (it does unfortunately indeed come out allineated). Bracer also does not create any legends. However, if it would be helpful I could upload a comprehensive legend here.

Best regards,
Ida

**Comment by SabrinaITNL** [comment]
Hi Ida, 
thank you very much for your reply. 
Ok no problem, but it is indeed good to know! It saves me time in trying to tweak the parameters to get the same output. 
I'll just edit it in illustrator then.

Thank you again!
BW
Sabrina

**Comment by idalind** [comment]
No problem!
By the way, a legend with the various isotypes is created for each lineage tree if you run summarise with --infer_lineage. These colours are the same as for the clone networks.
