### ISSUE TITLE
Not all cells included in Bracer summarize output

### ISSUE THREAD

**Issue by SabrinaITNL** [Teichlab/bracer#50]
Hi, 
I noticed that not all cells are included in the _changeodb_ file that I obtain after running bracer summarize (even if I include the "--include_multiplets"option).
When I check for reconstructed BCRs sequences into the "filtered_BCR_seqs" folder, and I can find the text file with annotated BCRs, perfectly functional and with TPM annotation. 
Also, the "BCR_summary.txt" file states that 178 cells were included, while I have actually 275 folders as output of bracer assemble. 
Why are those almost 100 cells not included in the bracer summarize output?

Thank you for your attention!
Kind regards
Sabrina

**Comment by tAndreani** [comment]
I have a question not related, are you able to infer the network and infer the lineage tree? 

Thank you for any reply

**Comment by idalind** [comment]
Hi @SabrinaITNL, I do not immediately have a solution for this. Could you please send me the output from your bracer summarise run and a couple of examples of assemble output for cells that were included in the summary and cells missing in the summary so I can look into this issue?

**Comment by SabrinaITNL** [comment]
Dear @idalind, 
I found out what the problem was: I had renamed some of the Bracer output folders so the folder name and sample name weren't matching anymore. Changing back the name solved the problem. 

Thank you again for your quick reply!
Best regards 
Sabrina

Dear @tAndreani, 
Yes it works perfectly for my data. 
Best regards
Sabrina
