### ISSUE TITLE
Docker container is outdated and does not build

### ISSUE THREAD

**Issue by antonkulaga** [Teichlab/bracer#54]
I noticed that bracer container at dockerhub is 1 years old. I tried to build it from bracer Dockerfile but it does not build. I also noticed that it uses very outdated software versions

**Comment by nielsphk** [comment]
I have attempted to update the bracer workflow to work with more current versions of the software. The docker container can be found at https://hub.docker.com/repository/docker/nielsphk/bracer

**Comment by NickEngland** [comment]
The Dockerfile for Bracer should build now. I've updated all the dependencies and fixed the problems that that caused!
