### ISSUE TITLE
A compatibility with Networkx v2.0

### ISSUE THREAD

**Issue by mstubb** [Teichlab/bracer#6]
Quite a lot has changed in Networkx v2.0 (https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html) and it breaks `summarise`. 

For now, the requirements file specifies v1.11 exactly but we need to add v2.0 compatibility.

**Comment by Japrin** [comment]
For example, the code in 1226 line of bracer_func.py:
`to_remove = [n for n in deg if deg[n] == 0]`
works for Networkx v1.111, but for Networkx v2.0, it should be changed to
`to_remove = [n for n in deg if n[1] == 0]`

**Comment by NickEngland** [comment]
This is now fixed in v0.2
