### ISSUE TITLE
Can BraCeR be used in other species' data?

### ISSUE THREAD

**Issue by jchenpku** [Teichlab/bracer#73]
I'd like to try it on species such as Rat. Thanks.

**Comment by NickEngland** [comment]
Hi @jchenpku , you can indeed use BraCeR on other species. You will need to create the appropriate reference for them, which is explained in the documentation.

Use "bracer build" as described here: https://github.com/Teichlab/bracer#build-build-combinatorial-recombinomes-for-a-given-species

Let me know if you have any problems!
