### ISSUE TITLE
Dockerfile needs to change Phylip download link

### ISSUE THREAD

**Issue by ulyssebaruchel** [Teichlab/bracer#81]
Hi, 
The Phylip link in the Dockerfile does not work anymore.  I think it must be replaced by https://phylipweb.github.io/phylip/download/phylip-3.697.tar.gz.

And I think this has been raised before, but I was wondering if there was any plan to make a bioconda package for BraCeR, please? Or at least a Singularity biocontainer maybe?

Thank you

**Comment by NickEngland** [comment]
Hi @ulyssebaruchel,

Thank you for bringing this to my attention, I've fixed the Phylip download link in the docker file.

We don't currently have plans to make a bioconda package, would a singularity biocontainer be more useful than the current docker container which can be converted to singularity?

**Comment by ulyssebaruchel** [comment]
Dear @NickEngland, thank you for your answer. A functional and ready-made singularity biocontainer would amazing, please, especially because a colleague and I have not been able to build the Docker image from the Docker file even after fixing the Phylip link and trying to fix other errors that popped up.

**Comment by NickEngland** [comment]
Hi @ulyssebaruchel , I've pushed https://github.com/Teichlab/bracer/releases/tag/v0.2.1 with an attached Singularity container for now. It's not biocontainer compliant, but I don't have the time to make those changes right now. If you do, feel free to issue a pull request!

**Comment by ulyssebaruchel** [comment]
Dear @NickEngland, thank you so much! Will try to do it if a pipeline using it gets deployed or published.

**Comment by NickEngland** [comment]
Great! Let me know how you get on. I'll close this issue now.
