### ISSUE TITLE
Question about fastq input

### ISSUE THREAD

**Issue by arnaudmgh** [Teichlab/bracer#84]
Hello, 

this is more a clarifying question than an issue:

it seems from the description that the an input fastq must have only reads from a unique cell to run. Typically, a fastq has reads for many (barcoded) cells. Therefore, one has first to parse the fastq to separate the single cells into one fastq per single cell, and only then run the tool, single cell per single cell?

Thank you!

**Comment by NickEngland** [comment]
Hi Arnaud,

BraCeR was written for smart-seq2 sequencing where each cell is in a physical well and barcoded as such. This is normally then split out into separate fastq files by the Illumina default processing at the sequencing facility.
 
If you want to run VDJ analysis on a 10X run, then other tools such as TRUST4 or the 10X CellRanger VDJ pipeline will work without needing to split the fastq file up first.
 
You can in principle split up the fastq for each cell barcode, and run them through BraCeR, but it's not supported currently.

(I answered this already by email, but I'm including my reply here as well in case it helps someone else in the future!)
